name: DOWNLOAD

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Executar script de download
      run: python DOWNLOAD.py

    - name: Atualizar timestamp nos arquivos baixados
      run: |
        echo "# Atualizado em $(date)" >> downloads/arquivo_1.m3u

    - name: Confirmar arquivos baixados
      run: ls -la downloads

    - name: Verificar mudanças no Git
      id: git_status
      run: echo "::set-output name=changes::$(git status --porcelain)"

    - name: Commit e push do arquivo baixado (se houver mudanças)
      if: steps.git_status.outputs.changes != ''
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add downloads/
        git commit -m "Atualização automática dos arquivos baixados"
        git push https://x-access-token:${{ secrets.MY_DOWNLOAD_GITHUB_TOKEN }}@github.com/josieljluz/m3u4u.com.git main
